# ===================================================================
# Configurações Padrão
# ===================================================================
server:
  port: 8082

spring:
  application:
    name: notificador

aws:
  sqs:
    queue-name: ${SQS_QUEUE_NAME}

---
# ===================================================================
# Perfil 'local' - Para Desenvolvimento com LocalStack
# ===================================================================
spring:
  config:
    activate:
      on-profile: "local"

  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
aws:
  sqs:
    queue-name: "zips-gerados-queue"
  sns:
    topic-arn: "arn:aws:sns:us-east-1:000000000000:notificacoes-topico"

---
# ===================================================================
# Perfil 'prod' - Para Produção
# ===================================================================
spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
aws:
  sns:
    topic-arn: ${SNS_TOPIC_ARN}
