server:
  port: 8082

spring:
  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:edb6efcff8bc4c}
    password: ${MAIL_PASSWORD:faecec4d46ed05}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
        session-token: ${AWS_SESSION_TOKEN}
      region:
        static: us-east-1

app:
  messaging:
    sqs:
      consumer:
        queueName: zips-gerados-queue.fifo     # ou defina queueUrl diretamente
        region: us-east-1
        endpoint: ${AWS_ENDPOINT:http://localhost:4566}
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
        sessionToken: ${AWS_SESSION_TOKEN}
        maxMessages: 10
        waitTimeSeconds: 10
        visibilityTimeoutSeconds: 60    # aplica ao receive (opcional)
        extendVisibilitySeconds: 120    # estende periodicamente durante o processamento (0=desabilita)
        pollIntervalMillis: 1000
        concurrency: 4
