version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_notificador
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data: