name: CI/CD Pipeline Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/notificador
jobs:
  build_and_test:
    name: Compilar, Testar e Construir Artefacto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Executar testes
        run: mvn -B test --file pom.xml
      - name: Construir o pacote (package)
        run: mvn -B package -DskipTests
      - name: Arquivar o artefacto JAR
        uses: actions/upload-artifact@v4
        with:
          name: notificador-jar
          path: target/*.jar

  push_to_dockerhub:
    name: Construir e Publicar Imagem Docker
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Descarregar artefacto JAR
        uses: actions/download-artifact@v4
        with:
          name: notificador-jar
          path: target/
      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Construir e enviar a imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
